### ISSUE TITLE
...ka

### ISSUE THREAD

**Issue by romebell** [SEI802/unit-1#3]
## Part 1 
- [x] [functions-dom-deliverable](https://github.com/SEI802/functions-dom-deliverable)
- [x] [unit-1-assessment - send link to deployed site](https://github.com/SEI802/unit-1-assessment)
- [x] [sql-zoo](https://github.com/SEI802/sql-zoo)

**Comment by romebell** [comment]
## Part 2
- [ ] [prehistoric-creatures](https://github.com/SEI802/prehistoric_creatures)
- [x] [challenge-problems-1](https://github.com/SEI802/challenge-problems-1)
- [x] [node_modules_practice](https://github.com/SEI802/node_modules_practice)

**Comment by romebell** [comment]
## Part 3
- [ ] [cities-app](https://github.com/SEI802/cities-app)
- [ ] [sequelize-cities-countries (Part 1 and Part 2)](https://github.com/SEI802/sequelize-cities-countries)
- [x] [express-pokedex](https://github.com/SEI802/express-pokedex)

**Comment by romebell** [comment]
- [ ] [ecommerce-api](https://github.com/SEI802/ecommerce-api)
- [ ] [Functional to Class Components](https://github.com/SEI802/react-functional-to-class)
- [ ] [React Star Wars](https://github.com/SEI802/react-star-wars)
- [ ] [React Burger Stacker](https://github.com/SEI802/react-burger-stacker)
