### ISSUE TITLE
...jk

### ISSUE THREAD

**Issue by romebell** [SEI802/unit-1#4]
## Part 1
- [x] [prehistoric-creatures](https://github.com/SEI802/prehistoric_creatures)
- [x] [challenge-problems-1](https://github.com/SEI802/challenge-problems-1)

**Comment by romebell** [comment]
## Part 2
- [x] [node_modules_practice](https://github.com/SEI802/node_modules_practice)
- [x] [sequelize-cities-countries (Part 1 and Part 2)](https://github.com/SEI802/sequelize-cities-countries)
- [x] [express-pokedex](https://github.com/SEI802/express-pokedex)
