### ISSUE TITLE
...re

### ISSUE THREAD

**Issue by romebell** [SEI802/unit-1#5]
## Part 1
- [x] [fetch-reddit-slideshow](https://github.com/SEI802/fetch-reddit-slideshow)
- [x] [sql-zoo Part 1 only](https://github.com/SEI802/sql-zoo)
- [ ] [node_modules_practice](https://github.com/SEI802/node_modules_practice)

**Comment by romebell** [comment]
## Part 2
- [ ] [prehistoric-creatures](https://github.com/SEI802/prehistoric_creatures)
- [ ] [cities-app](https://github.com/SEI802/cities-app)
- [x] [sequelize-cities-countries (Part 1 and Part 2)](https://github.com/SEI802/sequelize-cities-countries)
- [ ] [express-pokedex](https://github.com/SEI802/express-pokedex)
